### ISSUE TITLE
Modifying book doesn't enable save button

### ISSUE THREAD

**Issue by mstahv** [vaadin/bookstore-starter-flow#23]
The UI just feels broken as save button isn't enabled when changes are made to the book

**Comment by pekam** [comment]
This issue exists because by default the V10 `TextField` synchronizes it's value on `change` events. I created a fix for it which changes the fields to use eager synchronization: https://github.com/vaadin/bookstore-starter-flow/pull/35.

However, there's a reason why this is not the default behavior. It sends events on every key-press, which causes unnecessary network traffic.

V8 by default debounces the events, which would be the optimal behavior, but this is not possible in V10 with the component APIs. With the element API it is possible to debounce an event, eg.
```java
textField.getElement()
        .addEventListener("value-changed", e -> handleEvent(e))
        .debounce(500);
```
but `Binder` uses the component-level `HasValue` and `AbstractField` APIs to bind the values, so this doesn't help.

So we have to consider is it worth it to send the value changes eagerly to allow instant bean validation.

**Comment by mstahv** [comment]
I hope this kind of issues would yield to fixes/enhancements in components/framework. If we just keep adding workarounds to our demos, our customers will never be happy with Vaadin.

I'd consider missing LAZY mode as a bug in V10 and I think Binder should automatically configure text fields to use it if there is a status change listener in it. I think/hope there is an issue for the first one, but is there a one for the second?

**Comment by pekam** [comment]
I don't think Binder should override any ValueChangeModes of the fields, neither the default one or a value that has been set explicitly by the user.

Instead the field components should just use the LAZY mode by default.
